#!/bin/bash

MINTEMP=35
MAXTEMP=65
MINPWM=150
MAXPWM=255

start() {
  while :; do
    TEMP=$(nvidia-smi -q -i 0 -d TEMPERATURE | grep -m 1 "GPU Current Temp" | sed -E "s/^.*: ([0-9]+) C$/\1/")
    if [[ $TEMP -lt $MINTEMP ]]; then
      PWM=0
    elif [[ $TEMP -gt $MAXTEMP ]]; then
      PWM=$MAXPWM
    else
      PWM=$(($MINPWM + ((($MAXPWM - $MINPWM) / ($MAXTEMP - $MINTEMP)) * ($TEMP - $MINTEMP))))
    fi
    echo $PWM > /sys/class/hwmon/hwmon1/pwm3
    sleep 5
  done
}

stop() {
  echo 255 > /sys/class/hwmon/hwmon1/pwm3
}

case $1 in
  start|stop) "$1" ;;
esac
